//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReproBot.BotLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReproBot.BotLogic.BotResponses", typeof(BotResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let me get my calculator..
        /// </summary>
        public static string RootLuisDialog_CalculateInterest {
            get {
                return ResourceManager.GetString("RootLuisDialog_CalculateInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, have a nice day and don&apos;t be a stranger..
        /// </summary>
        public static string RootLuisDialog_EndConversation {
            get {
                return ResourceManager.GetString("RootLuisDialog_EndConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can perform a finance calculation for you..
        /// </summary>
        public static string RootLuisDialog_Help {
            get {
                return ResourceManager.GetString("RootLuisDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I did not understand &apos;{0}&apos;. Type &apos;help&apos; if you need assistance..
        /// </summary>
        public static string RootLuisDialog_None {
            get {
                return ResourceManager.GetString("RootLuisDialog_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, let me crunch some numbers..
        /// </summary>
        public static string RootLuisDialog_ResumeAfterCalculation_Confirmation {
            get {
                return ResourceManager.GetString("RootLuisDialog_ResumeAfterCalculation_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything else I can do?.
        /// </summary>
        public static string RootLuisDialog_ResumeAfterCalculation_OfferMore {
            get {
                return ResourceManager.GetString("RootLuisDialog_ResumeAfterCalculation_OfferMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rental re-payment will be {0} euro&apos;s based on a {1} {2} {3} month {4}% finance..
        /// </summary>
        public static string RootLuisDialog_ResumeAfterCalculation_Result {
            get {
                return ResourceManager.GetString("RootLuisDialog_ResumeAfterCalculation_Result", resourceCulture);
            }
        }
    }
}
